/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "customFields": {
    "nodeEnv": "production"
  },
  "title": "Jingo",
  "tagline": "Documentation and Guides",
  "url": "https://docs.pegasys.fi",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "ignore",
  "favicon": "img/pegasys.png",
  "organizationName": "Jingo-fi",
  "projectName": "Jingo-fi-docs",
  "themeConfig": {
    "image": "img/twitter_card_bg.jpg",
    "prism": {
      "additionalLanguages": [
        "solidity"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "apiKey": "94695b27d67e29001e39d689d2e9cce9",
      "indexName": "v3-docs",
      "appId": "ULGD82ZSGJ",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "title": "Jingo-fi Docs",
      "logo": {
        "alt": "Jingo-fi Unicorn",
        "src": "img/logoPegasys.svg"
      },
      "items": [
        {
          "to": "/concepts/overview",
          "label": "Concepts",
          "position": "left",
          "className": "V1_active"
        },
        {
          "to": "/contracts/v1/overview",
          "label": "Contracts",
          "position": "left",
          "className": "V1_active"
        },
        {
          "to": "/sdk/v1/overview",
          "label": "SDKs",
          "position": "left",
          "className": "V1_active"
        },
        {
          "to": "/api/subgraph/overview",
          "label": "APIs",
          "position": "left",
          "className": "V1_active"
        },
        {
          "label": "Litepaper",
          "to": "https://pegasys.fi/blog/introducing-pegasys/",
          "position": "right",
          "className": "persistent"
        },
        {
          "href": "https://github.com/pegasys-fi/docs",
          "label": "GitHub",
          "position": "right",
          "className": "persistent"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [
        {
          "title": "Developers",
          "items": [
            {
              "label": "#dev-chat",
              "href": "https://discord.com/invite/UzjWbWWERz"
            },
            {
              "label": "Litepaper",
              "href": "https://pegasys.fi/blog/introducing-pegasys/"
            },
            {
              "label": "Whitepaper (Uniswap v3)",
              "href": "https://uniswap.org/whitepaper-v3.pdf"
            }
          ]
        },
        {
          "title": "Github",
          "items": [
            {
              "label": "v3-core",
              "href": "https://github.com/Jingo-Finance/v3-core"
            },
            {
              "label": "v3-sdk",
              "href": "https://github.com/Jingo-Finance/v3-sdk"
            },
            {
              "label": "v3-periphery",
              "href": "https://github.com/Jingo-Finance/v3-periphery"
            }
          ]
        },
        {
          "title": "Ecosystem",
          "items": [
            {
              "label": "Home",
              "href": "https://pegasys.fi/"
            },
            {
              "label": "App",
              "href": "https://app.jingo.finance/"
            },
            {
              "label": "Analytics",
              "href": "https://info.jingo.finance/home"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.com/invite/UzjWbWWERz"
            },
            {
              "label": "Twitter",
              "href": "https://x.com/JingoFinance"
            }
          ]
        }
      ],
      "style": "light"
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "id": "contracts",
          "path": "docs/contracts",
          "routeBasePath": "contracts/",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ],
          "editUrl": "https://github.com/pegasys-fi/docs/tree/main/",
          "includeCurrentVersion": true
        },
        "blog": {
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ],
          "path": "blog/",
          "blogTitle": "Engineering Blog",
          "blogSidebarCount": 0
        },
        "theme": {
          "customCss": "/Users/imac/Desktop/Github/docs/src/css/custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "@saucelabs/theme-github-codeblock",
      {}
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "sdk",
        "path": "docs/sdk",
        "routeBasePath": "sdk",
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "includeCurrentVersion": true
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "api",
        "path": "docs/api",
        "routeBasePath": "api/",
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "includeCurrentVersion": true
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "concepts",
        "path": "docs/concepts",
        "routeBasePath": "concepts/",
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "includeCurrentVersion": true
      }
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "to": "/sdk/v3/guides/background",
            "from": "/sdk/v3/guides/quick-start"
          },
          {
            "to": "/sdk/v3/guides/quoting",
            "from": [
              "/sdk/v3/guides/creating-a-pool",
              "/sdk/v1/guides/fetching-prices"
            ]
          },
          {
            "to": "/sdk/v3/guides/trading",
            "from": "/sdk/v3/guides/creating-a-trade"
          },
          {
            "to": "/sdk/v3/guides/routing",
            "from": "/sdk/v3/guides/auto-router"
          },
          {
            "to": "/sdk/v3/guides/liquidity/modifying-position",
            "from": [
              "/sdk/v3/guides/liquidity/adding",
              "/sdk/v3/guides/liquidity/removing"
            ]
          }
        ]
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
